repos:
  - repo: local
    hooks:
      - id: style
        name: ruff check
        entry: hatch run lint:style
        language: system
        pass_filenames: false
        files: ^llm-observability-sdk/

      - id: format
        name: ruff format
        entry: hatch run lint:format
        language: system
        pass_filenames: false
        files: ^llm-observability-sdk/

      - id: typing
        name: mypy
        entry: hatch run lint:typing
        language: system
        pass_filenames: false
        files: ^llm-observability-sdk/

      - id: security
        name: bandit
        entry: hatch run lint:security
        language: system
        pass_filenames: false
        files: ^llm-observability-sdk/
